---

- name: check for variables
  when: >
    (vars[item] is not defined) or
    ( vars[item] is defined and not vars[item] ) or
    ( vars[item] is defined and vars[item]|length == 0 )
  with_items: "{{ tunnelbroker_required }}"
  fail:
    msg: >
      Required variables not defined or empty.

- name: ensure network-scripts directory exists
  file:
    path: /etc/sysconfig/network-scripts
    state: directory
    mode: 0755
    owner: root
    group: root

- name: tunnelbroker interface configuration
  template:
    src: templates/ifcfg.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ tunnelbroker_interface }}
    owner: root
    group: root
    mode: 0644
  register: tunnelbroker_configuration_a

- name: tunnelbroker interface configuration
  lineinfile:
    path: /etc/sysconfig/network
    regexp: "^IPV6_DEFAULTDEV="
    line: "IPV6_DEFAULTDEV={{ tunnelbroker_interface }}"
    create: yes
    owner: root
    group: root
    mode: 0644
  register: tunnelbroker_configuration_b

- name: tunnelbroker restart
  command: bash -c "ifdown {{ tunnelbroker_interface }} && ifup {{ tunnelbroker_interface }}"
  when: (tunnelbroker_role_debug|bool == false) and (tunnelbroker_configuration_a.changed or tunnelbroker_configuration_b.changed)
