---

- name: tunnelbroker reload
  systemd:
    daemon_reload: yes

- name: tunnelbroker restart
  systemd:
    name: tunnelbroker
    state: restarted
    enabled: yes
  when: not tunnelbroker_role_debug|bool
